# Generated by Django 4.1.7 on 2023-05-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_account_type_districts_palakkad_thrissur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_type',
        ),
        migrations.DeleteModel(
            name='Palakkad',
        ),
        migrations.DeleteModel(
            name='Thrissur',
        ),
        migrations.AlterField(
            model_name='check',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
    ]
